import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/whatToolsBlog/src/.vuepress/.temp/pages/server/serverInitializationUsage.html.vue"
const data = JSON.parse("{\"path\":\"/server/serverInitializationUsage.html\",\"title\":\"🧐 服务器的初始化使用\",\"lang\":\"zh-CN\",\"frontmatter\":{\"sticky\":96,\"title\":\"🧐 服务器的初始化使用\",\"tag\":[\"服务器\"],\"top\":6,\"recommend\":1,\"description\":\"连接命令 细节 ​ 如果此时你已经连接过了,然后你又重装了服务器的系统 ​ 当你再次连接的时候是无法连接上的 ​ 基本的错误如下 解释: ​ 这个警告消息表明指定IP地址（1.94.2.139）的主机密钥自上次保存在你的known_hosts文件之后已经更改。这可能是一个合法的变化，比如服务器的升级或配置更改. ​ 当你第一次连接的时候,你的电脑会记录...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/server/serverInitializationUsage.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🧐 服务器的初始化使用\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"连接命令 细节 ​ 如果此时你已经连接过了,然后你又重装了服务器的系统 ​ 当你再次连接的时候是无法连接上的 ​ 基本的错误如下 解释: ​ 这个警告消息表明指定IP地址（1.94.2.139）的主机密钥自上次保存在你的known_hosts文件之后已经更改。这可能是一个合法的变化，比如服务器的升级或配置更改. ​ 当你第一次连接的时候,你的电脑会记录...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"服务器\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🧐 服务器的初始化使用\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"连接命令\",\"slug\":\"连接命令\",\"link\":\"#连接命令\",\"children\":[]},{\"level\":2,\"title\":\"2. SSH 秘钥连接\",\"slug\":\"_2-ssh-秘钥连接\",\"link\":\"#_2-ssh-秘钥连接\",\"children\":[{\"level\":3,\"title\":\"2.1 制作密钥对\",\"slug\":\"_2-1-制作密钥对\",\"link\":\"#_2-1-制作密钥对\",\"children\":[]},{\"level\":3,\"title\":\"2.2 在服务器上安装公钥\",\"slug\":\"_2-2-在服务器上安装公钥\",\"link\":\"#_2-2-在服务器上安装公钥\",\"children\":[]},{\"level\":3,\"title\":\"2.3. 设置 SSH，打开密钥登录功能\",\"slug\":\"_2-3-设置-ssh-打开密钥登录功能\",\"link\":\"#_2-3-设置-ssh-打开密钥登录功能\",\"children\":[]},{\"level\":3,\"title\":\"2.4 本地秘钥配置\",\"slug\":\"_2-4-本地秘钥配置\",\"link\":\"#_2-4-本地秘钥配置\",\"children\":[]},{\"level\":3,\"title\":\"2.5 上传自己的秘钥\",\"slug\":\"_2-5-上传自己的秘钥\",\"link\":\"#_2-5-上传自己的秘钥\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.52,\"words\":756},\"filePathRelative\":\"server/serverInitializationUsage.md\",\"excerpt\":\"<h2>连接命令</h2>\\n<div class=\\\"language-bash\\\" data-ext=\\\"sh\\\" data-title=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"token function\\\">ssh</span> root@ip\\n<span class=\\\"token comment\\\"># 然后会让你输入密码</span>\\nxxxxx  \\n<span class=\\\"token comment\\\"># 成功进入</span>\\n</code></pre></div><blockquote>\\n<p>细节</p>\\n<p>​\\t如果此时你已经连接过了,然后你又重装了服务器的系统</p>\\n<p>​\\t当你再次连接的时候是无法连接上的</p>\\n<p>​\\t基本的错误如下</p>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
