import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/whatToolsBlog/src/.vuepress/.temp/pages/server/git/commonCommands.html.vue"
const data = JSON.parse("{\"path\":\"/server/git/commonCommands.html\",\"title\":\"🥹 git 常用命令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🥹 git 常用命令\",\"tag\":[\"git\"],\"star\":true,\"description\":\"分支相关 查看本地和远程所有分支 查看本地所有分支 切换本地指定分支 新建分支 删除本地分支 提交代码 将本地 a 的代码提交到远程 b 分支 代码回退 回退到上一个提交 回退到指定的提交 代码合并 分支合并 commit id 合并 其他 查看本地提交log 添加远程仓库地址 查看远程的仓库地址 git stash 临时保存工作目录中已跟踪文件和暂存...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/server/git/commonCommands.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🥹 git 常用命令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"分支相关 查看本地和远程所有分支 查看本地所有分支 切换本地指定分支 新建分支 删除本地分支 提交代码 将本地 a 的代码提交到远程 b 分支 代码回退 回退到上一个提交 回退到指定的提交 代码合并 分支合并 commit id 合并 其他 查看本地提交log 添加远程仓库地址 查看远程的仓库地址 git stash 临时保存工作目录中已跟踪文件和暂存...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"git\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🥹 git 常用命令\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"分支相关\",\"slug\":\"分支相关\",\"link\":\"#分支相关\",\"children\":[]},{\"level\":2,\"title\":\"提交代码\",\"slug\":\"提交代码\",\"link\":\"#提交代码\",\"children\":[]},{\"level\":2,\"title\":\"代码回退\",\"slug\":\"代码回退\",\"link\":\"#代码回退\",\"children\":[]},{\"level\":2,\"title\":\"代码合并\",\"slug\":\"代码合并\",\"link\":\"#代码合并\",\"children\":[]},{\"level\":2,\"title\":\"其他\",\"slug\":\"其他\",\"link\":\"#其他\",\"children\":[]}],\"readingTime\":{\"minutes\":2.36,\"words\":709},\"filePathRelative\":\"server/git/commonCommands.md\",\"excerpt\":\"<h2>分支相关</h2>\\n<blockquote>\\n<p>查看本地和远程所有分支</p>\\n</blockquote>\\n<div class=\\\"language-bash\\\" data-ext=\\\"sh\\\" data-title=\\\"sh\\\"><pre class=\\\"language-bash\\\"><code><span class=\\\"token function\\\">git</span> br <span class=\\\"token parameter variable\\\">-a</span> \\n</code></pre></div><blockquote>\\n<p>查看本地所有分支</p>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
