import comp from "/Users/zeroeldath/Desktop/ignore-space/what-tools-blog/src/.vuepress/.temp/pages/web/Vue/vue-router.html.vue"
const data = JSON.parse("{\"path\":\"/web/Vue/vue-router.html\",\"title\":\"🪤 vue-router\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🪤 vue-router\",\"tag\":[\"Vue\",\"vue-router\"],\"description\":\"🪤 vue-router 路由的相关知识点 前端路由 前端路由是后来发展到SPA（单页应用）时才出现的概念。 SPA 就是一个WEB项目只有一个 HTML 页面，一旦页面加载完成，SPA 不会因为用户的操作而进行页面的重新加载或跳转。 前端路由在SPA项目中是必不可少的，页面的跳转、刷新都与路由有关，通过不同的url显示相应的页面。 优点：前后端的彻...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/Vue/vue-router.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🪤 vue-router\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"🪤 vue-router 路由的相关知识点 前端路由 前端路由是后来发展到SPA（单页应用）时才出现的概念。 SPA 就是一个WEB项目只有一个 HTML 页面，一旦页面加载完成，SPA 不会因为用户的操作而进行页面的重新加载或跳转。 前端路由在SPA项目中是必不可少的，页面的跳转、刷新都与路由有关，通过不同的url显示相应的页面。 优点：前后端的彻...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"vue-router\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🪤 vue-router\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"路由的相关知识点\",\"slug\":\"路由的相关知识点\",\"link\":\"#路由的相关知识点\",\"children\":[{\"level\":3,\"title\":\"前端路由\",\"slug\":\"前端路由\",\"link\":\"#前端路由\",\"children\":[]},{\"level\":3,\"title\":\"后端路由\",\"slug\":\"后端路由\",\"link\":\"#后端路由\",\"children\":[]},{\"level\":3,\"title\":\"路由模式\",\"slug\":\"路由模式\",\"link\":\"#路由模式\",\"children\":[]}]},{\"level\":2,\"title\":\"Vue2 | vue-router@3\",\"slug\":\"vue2-vue-router-3\",\"link\":\"#vue2-vue-router-3\",\"children\":[]},{\"level\":2,\"title\":\"Vue3 | vue-router@4\",\"slug\":\"vue3-vue-router-4\",\"link\":\"#vue3-vue-router-4\",\"children\":[]}],\"readingTime\":{\"minutes\":5.67,\"words\":1702},\"filePathRelative\":\"web/Vue/vue-router.md\",\"excerpt\":\"\\n<h2>路由的相关知识点</h2>\\n<h3>前端路由</h3>\\n<blockquote>\\n<p>前端路由是后来发展到SPA（单页应用）时才出现的概念。 SPA 就是一个WEB项目只有一个 HTML 页面，一旦页面加载完成，SPA 不会因为用户的操作而进行页面的重新加载或跳转。</p>\\n</blockquote>\\n<p>前端路由在SPA项目中是必不可少的，页面的跳转、刷新都与路由有关，通过不同的url显示相应的页面。</p>\\n<p>优点：前后端的彻底分离，不刷新页面，用户体验较好，页面持久性较好。</p>\\n<h3>后端路由</h3>\\n<p>当在地址栏切换不同的url时，都会向服务器发送一个请求，服务器接收并响应这个请求，在服务端拼接好html文件返回给页面来展示。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
