import comp from "/Users/zeroeldath/Desktop/ignore-space/what-tools-blog/src/.vuepress/.temp/pages/web/network-request/websocket.html.vue"
const data = JSON.parse("{\"path\":\"/web/network-request/websocket.html\",\"title\":\"🤕 WebSocket 快速使用教程\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🤕 WebSocket 快速使用教程\",\"tag\":[\"WebSocket\",\"前端\"],\"description\":\"WebSocket 使用教程 创建 WebSocket 对象： 在括号内，要指定 WebSocket 服务器的 URL。注意要使用 \\\"wss://\\\" 开头来表示安全的 WebSocket 连接，如果是非安全的连接则使用 \\\"ws://\\\"。 监听 WebSocket 事件： onopen 事件在 WebSocket 连接建立后触发。 onmessage 事...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/network-request/websocket.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🤕 WebSocket 快速使用教程\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"WebSocket 使用教程 创建 WebSocket 对象： 在括号内，要指定 WebSocket 服务器的 URL。注意要使用 \\\"wss://\\\" 开头来表示安全的 WebSocket 连接，如果是非安全的连接则使用 \\\"ws://\\\"。 监听 WebSocket 事件： onopen 事件在 WebSocket 连接建立后触发。 onmessage 事...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"WebSocket\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🤕 WebSocket 快速使用教程\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"使用教程\",\"slug\":\"使用教程\",\"link\":\"#使用教程\",\"children\":[]}],\"readingTime\":{\"minutes\":0.58,\"words\":175},\"filePathRelative\":\"web/network-request/websocket.md\",\"excerpt\":\"\\n<h2>使用教程</h2>\\n<ol>\\n<li>创建 WebSocket 对象：</li>\\n</ol>\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code><span class=\\\"token keyword\\\">const</span> socket <span class=\\\"token operator\\\">=</span> <span class=\\\"token keyword\\\">new</span> <span class=\\\"token class-name\\\">WebSocket</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token string\\\">\\\"wss://example.com/socket\\\"</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
