export const categoriesMap = {"category":{"/":{"path":"/category/","map":{}}},"tag":{"/":{"path":"/tag/","map":{"面试":{"path":"/tag/面试/","indexes":[0,1]},"Javascript":{"path":"/tag/javascript/","indexes":[0,2]},"Vue":{"path":"/tag/vue/","indexes":[1,3,4,5]},"图床":{"path":"/tag/图床/","indexes":[6,7]},"服务器":{"path":"/tag/服务器/","indexes":[8]},"Maven":{"path":"/tag/maven/","indexes":[9]},"JavaWeb":{"path":"/tag/javaweb/","indexes":[10,9,11,12,13,14,15,16,17,18,19,20,21]},"SpringBoot":{"path":"/tag/springboot/","indexes":[10,11,12,13,14,15,16,17,18,19,20,21]},"Mybatis-plus":{"path":"/tag/mybatis-plus/","indexes":[11]},"Redis":{"path":"/tag/redis/","indexes":[12]},"Spring":{"path":"/tag/spring/","indexes":[13]},"Mybatis":{"path":"/tag/mybatis/","indexes":[16,17]},"JWT":{"path":"/tag/jwt/","indexes":[18]},"Swagger":{"path":"/tag/swagger/","indexes":[20]},"Java":{"path":"/tag/java/","indexes":[22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55]},"MySql":{"path":"/tag/mysql/","indexes":[56,57,58]},"node":{"path":"/tag/node/","indexes":[59]},"nvm":{"path":"/tag/nvm/","indexes":[59]},"NGINX":{"path":"/tag/nginx/","indexes":[60]},"封装":{"path":"/tag/封装/","indexes":[60,61]},"前端":{"path":"/tag/前端/","indexes":[62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78]},"Echarts":{"path":"/tag/echarts/","indexes":[62]},"React":{"path":"/tag/react/","indexes":[63,65,78]},"ffmpeg":{"path":"/tag/ffmpeg/","indexes":[63]},"video":{"path":"/tag/video/","indexes":[63]},"Google Drive":{"path":"/tag/google-drive/","indexes":[64]},"vue-router":{"path":"/tag/vue-router/","indexes":[3]},"vuex":{"path":"/tag/vuex/","indexes":[4]},"pinia":{"path":"/tag/pinia/","indexes":[4]},"QrCode":{"path":"/tag/qrcode/","indexes":[65]},"CSS":{"path":"/tag/css/","indexes":[79]},"axios":{"path":"/tag/axios/","indexes":[61,78]},"正则表达式":{"path":"/tag/正则表达式/","indexes":[80]},"工具":{"path":"/tag/工具/","indexes":[80]},"three.js":{"path":"/tag/three.js/","indexes":[81,82]},"uni-app":{"path":"/tag/uni-app/","indexes":[83]},"AJAX":{"path":"/tag/ajax/","indexes":[66]},"XHR":{"path":"/tag/xhr/","indexes":[66]},"WebSocket":{"path":"/tag/websocket/","indexes":[67]},"Webpack":{"path":"/tag/webpack/","indexes":[68,84,70]},"优化":{"path":"/tag/优化/","indexes":[69,70,71,72]},"Gulp":{"path":"/tag/gulp/","indexes":[69]},"babel":{"path":"/tag/babel/","indexes":[70]},"SEO":{"path":"/tag/seo/","indexes":[72]},"Array":{"path":"/tag/array/","indexes":[85]},"算法":{"path":"/tag/算法/","indexes":[85,86]},"设计模式":{"path":"/tag/设计模式/","indexes":[73]},"pdfjs":{"path":"/tag/pdfjs/","indexes":[74]},"rollup":{"path":"/tag/rollup/","indexes":[75,76,77]},"SDK":{"path":"/tag/sdk/","indexes":[75,76]},"初始代码库":{"path":"/tag/初始代码库/","indexes":[78]},"antd":{"path":"/tag/antd/","indexes":[78]}}}}};

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept();
  if (__VUE_HMR_RUNTIME__.updateBlogCategory)
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoryMap);
}

if (import.meta.hot)
  import.meta.hot.accept(({ categoryMap }) => {
    __VUE_HMR_RUNTIME__.updateBlogCategory(categoryMap);
  });


