import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/whatToolsBlog/src/.vuepress/.temp/pages/web/learn-vue/3-communication-mode.html.vue"
const data = JSON.parse("{\"path\":\"/web/learn-vue/3-communication-mode.html\",\"title\":\"3. Vue中组件的通信方式\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"3. Vue中组件的通信方式\",\"tag\":[\"Vue\"],\"description\":\"Vue2 子组件中，使用 $emit 触发一个自定义事件，并传递需要传递的数据： 父组件中，监听子组件触发的自定义事件，并在事件处理函数中接收数据： Vue3 父子组件 emit 的方式 子组件传递 父组件接受 父组件获取子组件中的属性值 核心在于 子组件的 defineExpose({sex, info}) 子组件传递的方式 父组件显示的方式 为子组...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/learn-vue/3-communication-mode.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"3. Vue中组件的通信方式\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Vue2 子组件中，使用 $emit 触发一个自定义事件，并传递需要传递的数据： 父组件中，监听子组件触发的自定义事件，并在事件处理函数中接收数据： Vue3 父子组件 emit 的方式 子组件传递 父组件接受 父组件获取子组件中的属性值 核心在于 子组件的 defineExpose({sex, info}) 子组件传递的方式 父组件显示的方式 为子组...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.z4a.net/images/2024/06/10/imagede42eb2e9680d4f6.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"3. Vue中组件的通信方式\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Vue\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"3. Vue中组件的通信方式\\\",\\\"image\\\":[\\\"https://www.z4a.net/images/2024/06/10/imagede42eb2e9680d4f6.png\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Vue2\",\"slug\":\"vue2\",\"link\":\"#vue2\",\"children\":[]},{\"level\":2,\"title\":\"Vue3\",\"slug\":\"vue3\",\"link\":\"#vue3\",\"children\":[{\"level\":3,\"title\":\"父子组件\",\"slug\":\"父子组件\",\"link\":\"#父子组件\",\"children\":[]},{\"level\":3,\"title\":\"爷孙组件通信\",\"slug\":\"爷孙组件通信\",\"link\":\"#爷孙组件通信\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.25,\"words\":974},\"filePathRelative\":\"web/learn-vue/3-communication-mode.md\",\"excerpt\":\"<h2>Vue2</h2>\\n<p>子组件中，使用 $emit 触发一个自定义事件，并传递需要传递的数据：</p>\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code><span class=\\\"token comment\\\">// 子组件</span>\\n<span class=\\\"token keyword\\\">this</span><span class=\\\"token punctuation\\\">.</span><span class=\\\"token function\\\">$emit</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token string\\\">'custom-event'</span><span class=\\\"token punctuation\\\">,</span> data<span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
