import comp from "/Users/zeroeldath/Desktop/ignore-space/whatToolsBlog/src/.vuepress/.temp/pages/web/package/axios-shortcut.html.vue"
const data = JSON.parse("{\"path\":\"/web/package/axios-shortcut.html\",\"title\":\"🪤 axios 快捷封装\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🪤 axios 快捷封装\",\"tag\":[\"axios\",\"封装\"],\"description\":\"axios.pngaxios.png 依赖安装 封装体 使用 其他相关的 axios 知识 多请求发送 常用的请求配置 使用的评率由上往下依次递减 \",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/package/axios-shortcut.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🪤 axios 快捷封装\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"axios.pngaxios.png 依赖安装 封装体 使用 其他相关的 axios 知识 多请求发送 常用的请求配置 使用的评率由上往下依次递减 \"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://www.z4a.net/images/2023/10/07/axios.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"🪤 axios 快捷封装\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"axios\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"封装\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🪤 axios 快捷封装\\\",\\\"image\\\":[\\\"https://www.z4a.net/images/2023/10/07/axios.png\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"依赖安装\",\"slug\":\"依赖安装\",\"link\":\"#依赖安装\",\"children\":[]},{\"level\":2,\"title\":\"封装体\",\"slug\":\"封装体\",\"link\":\"#封装体\",\"children\":[]},{\"level\":2,\"title\":\"使用\",\"slug\":\"使用\",\"link\":\"#使用\",\"children\":[]},{\"level\":2,\"title\":\"其他相关的 axios 知识\",\"slug\":\"其他相关的-axios-知识\",\"link\":\"#其他相关的-axios-知识\",\"children\":[{\"level\":3,\"title\":\"多请求发送\",\"slug\":\"多请求发送\",\"link\":\"#多请求发送\",\"children\":[]},{\"level\":3,\"title\":\"常用的请求配置\",\"slug\":\"常用的请求配置\",\"link\":\"#常用的请求配置\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.57,\"words\":1370},\"filePathRelative\":\"web/package/axios-shortcut.md\",\"excerpt\":\"<figure><img src=\\\"https://www.z4a.net/images/2023/10/07/axios.png\\\" alt=\\\"axios.png\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>axios.png</figcaption></figure>\\n<h2>依赖安装</h2>\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code>npm install axios\\nor\\nyarn add axios\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
