import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/vuepress-hope-what-tools-blog/src/.vuepress/.temp/pages/web/component-packaging/index.html.vue"
const data = JSON.parse("{\"path\":\"/web/component-packaging/\",\"title\":\"🎃 组件 | SDK 封装\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🎃 组件 | SDK 封装\",\"tag\":[\"前端\",\"rollup\",\"SDK\"],\"description\":\"项目初始化 创建文件rollup.config.js Parcel 启动命令 yarn parcel src/index.html 一句话,做你任何你想做的事情,一切交给 parcel,包括依赖的自动安装 打包 发布npm npm adduser 用户名 密码 邮箱 邮箱验证码 npm login 输入刚才的 用户名 密码 邮箱 验证码 npm pub...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/web/component-packaging/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🎃 组件 | SDK 封装\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"项目初始化 创建文件rollup.config.js Parcel 启动命令 yarn parcel src/index.html 一句话,做你任何你想做的事情,一切交给 parcel,包括依赖的自动安装 打包 发布npm npm adduser 用户名 密码 邮箱 邮箱验证码 npm login 输入刚才的 用户名 密码 邮箱 验证码 npm pub...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Mr.Hope\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"前端\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"rollup\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"SDK\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🎃 组件 | SDK 封装\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"项目初始化\",\"slug\":\"项目初始化\",\"link\":\"#项目初始化\",\"children\":[]},{\"level\":2,\"title\":\"Parcel\",\"slug\":\"parcel\",\"link\":\"#parcel\",\"children\":[]},{\"level\":2,\"title\":\"发布npm\",\"slug\":\"发布npm\",\"link\":\"#发布npm\",\"children\":[]}],\"readingTime\":{\"minutes\":0.46,\"words\":139},\"filePathRelative\":\"web/component-packaging/index.md\",\"excerpt\":\"<h2>项目初始化</h2>\\n<p>创建文件rollup.config.js</p>\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code>npm init <span class=\\\"token operator\\\">-</span>y\\ntsc <span class=\\\"token operator\\\">--</span>init\\n\\n\\nnpm install rollup <span class=\\\"token operator\\\">-</span><span class=\\\"token constant\\\">D</span>\\nnpm install rollup<span class=\\\"token operator\\\">-</span>plugin<span class=\\\"token operator\\\">-</span>dts <span class=\\\"token operator\\\">-</span><span class=\\\"token constant\\\">D</span>\\nnpm install rollup<span class=\\\"token operator\\\">-</span>plugin<span class=\\\"token operator\\\">-</span>typescript2 <span class=\\\"token operator\\\">-</span><span class=\\\"token constant\\\">D</span>\\nnpm install typescript <span class=\\\"token operator\\\">-</span><span class=\\\"token constant\\\">D</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
