import comp from "D:/code/whatToolsBlog/src/.vuepress/.temp/pages/web/css/grid.html.vue"
const data = JSON.parse("{\"path\":\"/web/css/grid.html\",\"title\":\"🥴 Grid 布局\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🥴 Grid 布局\",\"tag\":[\"CSS\"],\"description\":\"父级 子元素\",\"gitInclude\":[],\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/css/grid.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🥴 Grid 布局\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"父级 子元素\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CSS\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🥴 Grid 布局\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"父级\",\"slug\":\"父级\",\"link\":\"#父级\",\"children\":[]},{\"level\":2,\"title\":\"子元素\",\"slug\":\"子元素\",\"link\":\"#子元素\",\"children\":[]}],\"readingTime\":{\"minutes\":0.31,\"words\":92},\"filePathRelative\":\"web/css/grid.md\",\"excerpt\":\"<h2>父级</h2>\\n<div class=\\\"language-css\\\" data-ext=\\\"css\\\" data-title=\\\"css\\\"><pre class=\\\"language-css\\\"><code><span class=\\\"token selector\\\">.wrapper</span> <span class=\\\"token punctuation\\\">{</span>\\n    <span class=\\\"token property\\\">display</span><span class=\\\"token punctuation\\\">:</span> flex<span class=\\\"token punctuation\\\">;</span>\\n    <span class=\\\"token comment\\\">/*grid-template-columns: 1fr 1fr 1fr;*/</span>  <span class=\\\"token comment\\\">/*设置列 4 列,每一列的宽度等均分配*/</span>\\n    <span class=\\\"token property\\\">grid-template-columns</span><span class=\\\"token punctuation\\\">:</span> <span class=\\\"token function\\\">repeat</span><span class=\\\"token punctuation\\\">(</span>auto-fill<span class=\\\"token punctuation\\\">,</span><span class=\\\"token function\\\">minmax</span><span class=\\\"token punctuation\\\">(</span>260px<span class=\\\"token punctuation\\\">,</span>1fr<span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span> <span class=\\\"token comment\\\">/*设置列 自动计算个数,每一列的宽度最小值和最大值*/</span>\\n    <span class=\\\"token property\\\">gap</span><span class=\\\"token punctuation\\\">:</span> 10px<span class=\\\"token punctuation\\\">;</span> <span class=\\\"token comment\\\">/*设置四周的间隙 */</span>\\n<span class=\\\"token punctuation\\\">}</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
