import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/whatToolsBlog/src/.vuepress/.temp/pages/web/common/Array.html.vue"
const data = JSON.parse("{\"path\":\"/web/common/Array.html\",\"title\":\"数组的相关算法\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"数组的相关算法\",\"tag\":[\"Array\",\"算法\"],\"description\":\"数组的相关算法 Reduce Demo 数组中所有值的和 累加对象数组里面的值 展平嵌套数组 统计对象中值的出现次数 按属性对对象进行分组 数组去重 按顺序运行 Promise \",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/common/Array.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"数组的相关算法\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"数组的相关算法 Reduce Demo 数组中所有值的和 累加对象数组里面的值 展平嵌套数组 统计对象中值的出现次数 按属性对对象进行分组 数组去重 按顺序运行 Promise \"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Array\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"算法\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"数组的相关算法\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Reduce\",\"slug\":\"reduce\",\"link\":\"#reduce\",\"children\":[{\"level\":3,\"title\":\"Demo\",\"slug\":\"demo\",\"link\":\"#demo\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.81,\"words\":543},\"filePathRelative\":\"web/common/Array.md\",\"excerpt\":\"\\n<h2>Reduce</h2>\\n<div class=\\\"language-javascript\\\" data-ext=\\\"js\\\" data-title=\\\"js\\\"><pre class=\\\"language-javascript\\\"><code>array<span class=\\\"token punctuation\\\">.</span><span class=\\\"token function\\\">reduce</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token punctuation\\\">(</span><span class=\\\"token parameter\\\">accumulator<span class=\\\"token punctuation\\\">,</span> currentValue<span class=\\\"token punctuation\\\">,</span>currentIndex<span class=\\\"token punctuation\\\">,</span>array</span><span class=\\\"token punctuation\\\">)</span><span class=\\\"token operator\\\">=&gt;</span> <span class=\\\"token punctuation\\\">{</span>\\n    <span class=\\\"token comment\\\">// accumulator:累加器 就是上一次 return 的值,初始值,第二个参数为空的时候就是数组的第一个值</span>\\n    <span class=\\\"token comment\\\">// currentValue:当前值</span>\\n    <span class=\\\"token comment\\\">// currentIndex:当前索引</span>\\n    <span class=\\\"token comment\\\">// array:数组</span>\\n    \\n<span class=\\\"token punctuation\\\">}</span><span class=\\\"token punctuation\\\">,</span> initialValue<span class=\\\"token punctuation\\\">)</span>\\n</code></pre></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
