import comp from "/Users/zeroeldath/Desktop/ignore-space/zero-eldath/whatToolsBlog/src/.vuepress/.temp/pages/web/harmony/7-lifeCycle.html.vue"
const data = JSON.parse("{\"path\":\"/web/harmony/7-lifeCycle.html\",\"title\":\"🦋 7-生命周期\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"🦋 7-生命周期\",\"tag\":[\"harmony\"],\"star\":true,\"description\":\"生命周期 EntryAbility 文件 hilog.info 日志 '%{public}s' public 表示日志是否公开 UIAbility 模式 修改模式 在每个 entry 的模块中 module.json5 ​ launchType Singleton 模式 只会存在一个后台的实例 Standard 模式 每次打开,创建一个新的实例,保留旧...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://soft-vault.com/web/harmony/7-lifeCycle.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"🦋 7-生命周期\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"生命周期 EntryAbility 文件 hilog.info 日志 '%{public}s' public 表示日志是否公开 UIAbility 模式 修改模式 在每个 entry 的模块中 module.json5 ​ launchType Singleton 模式 只会存在一个后台的实例 Standard 模式 每次打开,创建一个新的实例,保留旧...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Night.Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"harmony\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"🦋 7-生命周期\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Night.Soul\\\",\\\"url\\\":\\\"https://github.com/NightSquirrl\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"EntryAbility 文件\",\"slug\":\"entryability-文件\",\"link\":\"#entryability-文件\",\"children\":[]},{\"level\":2,\"title\":\"UIAbility 模式\",\"slug\":\"uiability-模式\",\"link\":\"#uiability-模式\",\"children\":[{\"level\":3,\"title\":\"Singleton 模式\",\"slug\":\"singleton-模式\",\"link\":\"#singleton-模式\",\"children\":[]},{\"level\":3,\"title\":\"Standard 模式\",\"slug\":\"standard-模式\",\"link\":\"#standard-模式\",\"children\":[]},{\"level\":3,\"title\":\"multiton模式\",\"slug\":\"multiton模式\",\"link\":\"#multiton模式\",\"children\":[]},{\"level\":3,\"title\":\"specified 模式\",\"slug\":\"specified-模式\",\"link\":\"#specified-模式\",\"children\":[]}]}],\"readingTime\":{\"minutes\":1.76,\"words\":528},\"filePathRelative\":\"web/harmony/7-lifeCycle.md\",\"excerpt\":\"\\n<iframe style=\\\"border: 1px solid rgba(0, 0, 0, 0.1);\\\" sandbox=\\\"allow-scripts allow-popups allow-forms allow-modals allow-same-origin\\\" width=\\\"800\\\" height=\\\"450\\\" src=\\\"https://pixso.cn/app/ifr?url=https://pixso.cn/app/board/bnFWVuhoAUXEjcEF2odNsg\\\" allowfullscreen=\\\"\\\"></iframe>\\n<h2>EntryAbility 文件</h2>\\n<blockquote>\\n<p>hilog.info 日志</p>\\n<p>'%{public}s'  public 表示日志是否公开</p>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
